name: AWS test suite

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://docs.aws.amazon.com/general/latest/gr/samples/aws-sig-v4-test-suite.zip --output "$RUNNER_TEMP/aws-sig-v4-test-suite.zip"
      - run: ls -la "$RUNNER_TEMP"
